######################################################################
# Automatically generated by qmake (3.0) Sat May 9 11:25:54 2015
######################################################################

TEMPLATE = app
TARGET = POS
INCLUDEPATH += .
QT += core gui widgets 

# Input
HEADERS += login.h \
    home.h \
    test.h
FORMS += login.ui \
    home.ui
SOURCES += login.cpp main.cpp \
    home.cpp \
    test.cpp
